### ISSUE TITLE
Errors running tests

### ISSUE THREAD

**Issue by cramatt** [DimiMikadze/create-react-library#3]
Running `yarn run test` produces the following error: 

```
yarn run v0.27.5
$ node scripts/test.js --env=jsdom
2017-09-01 12:56 node[30987] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-09-01 12:56 node[30987] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-09-01 12:56 node[30987] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1034:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1376:11)
```
And `npm run test` fails too:

```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-react-library@1.0.0 test: `node scripts/test.js --env=jsdom`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-react-library@1.0.0 test script 'node scripts/test.js --env=jsdom'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the create-react-library package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/test.js --env=jsdom
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs create-react-library
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls create-react-library
npm ERR! There is likely additional logging output above.
```

**Comment by DimiMikadze** [comment]
HI @cramatt,

can you tell me when this error shows up? have you modified something or tests fails right after pulling repository?

Btw i have noticed `npm` and `yarn` are producing very weird errors when both are used in project.
I suggest removing `node_modules`, `package-lock.json` and `yarn.lock` if present and run one more time `npm` or `yarn` install.
